--- #YAML:1.0
name:                Acme-Phlegethoth
version:             1.01
abstract:            Improve your code's readability, if you're an Ancient One
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_01
author:              Rocco Caputo <rcaputo@cpan.org>
distribution_type:   module
requires:     
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
