--- #YAML:1.0
name:               Acme-Phlegethoth
version:            1.04
abstract:           Improve your code's readability, if you're an Ancient One
author:
    - Rocco Caputo <rcaputo@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    license:     http://dev.perl.org/licenses/
    repository:  http://thirdlobe.com/svn/acme-phlegethoth/trunk
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
